apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-pv-3
spec:
  storageClassName: nfs-sc
  mountOptions:
    - hard
    - nfsvers=3
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.197.73.107"
    path: "/export/vol1"